AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  DenemeParam:
    Type: String
    Default: default deneme

Globals:
  Function:
    Runtime: nodejs14.x
    Timeout: 3

LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
              - !Join
                - ''
                - - states.
                  - !Ref 'AWS::Region'
                  - .amazonaws.com
              - sns.amazonaws.com
              - s3.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
Resources:

  GetTodos:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.getTodos
      Timeout: 30
      MemorySize: 128
      Role: !GetAtt 'LambdaExecutionRole.Arn'
      Environment:
        Variables:
          DenemeVariable: !Ref DenemeParam
      Events:
        HookPost:
          Type: Api
          Properties:
            Path: /todos
            Method: GET
